import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the data from the Excel file
df = pd.read_excel('') # Insert file path to excel document

# Prepare data for visualization
# Sum correct and incorrect identifications for human and GPT-generated feedback
correct_human = df['Feedback generated by human'].sum()
incorrect_human = len(df['Feedback generated by human']) - correct_human
correct_gpt = df['Feedback generated by GPT'].sum()
incorrect_gpt = len(df['Feedback generated by GPT']) - correct_gpt

# Create DataFrame for plotting
data = {
    'Correct ID': [correct_human, correct_gpt],
    'Incorrect ID': [incorrect_human, incorrect_gpt]
}
plot_df = pd.DataFrame(data, index=['Human', 'GPT'])

# Set the seaborn style for better aesthetics
sns.set(style="whitegrid")

# Set global font size to 18
plt.rcParams.update({'font.size': 18})

# Create a figure with specified size to adjust bulkiness and maintain consistency with the histogram
plt.figure(figsize=(6, 6))

# Plotting the stacked bar chart with matching colors
ax = plot_df.plot(kind='bar', stacked=True, color=['#3498db', '#e74c3c'], width=0.4)  # Adjusted width for bars
ax.set_xlabel('Feedback Generator')
ax.set_ylabel('Number of IDs')
ax.set_xticklabels(['Human', 'GPT'], rotation=0)  # Keep the labels horizontal for better readability

# Adjust the legend to be inside the graph
ax.legend(loc='upper right', bbox_to_anchor=(1, 1))

# Remove grid lines from the plot
ax.grid(False)

# Adjust layout to fit everything nicely
plt.tight_layout()

# Show the plot
plt.show()
